// app/layout.jsx
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import Providers from "./providers";
import ThemeWrapper from "./providers/ThemeProvider";
import { Toaster } from "sonner";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata = {
  title: "Alfalah Insurance Web Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <ThemeWrapper>
            {children}
            <Toaster richColors position="top-right" />
          </ThemeWrapper>
        </Providers>
      </body>
    </html>
  );
}
